server:
  host: localhost
  port: "8080"
  read_timeout: 30
  write_timeout: 30

database:
  host: localhost
  port: "5432"
  user: postgres
  password: postgres
  db_name: logistics_db
  ssl_mode: disable
  database_url: ""
  max_open_conns: 10
  max_idle_conns: 2

jwt:
  secret: temp-secret
  expiry_hour: 24

logger:
  level: debug
  format: json